package com.echoed.chamber.services.state.schema

import com.echoed.chamber.domain
import org.squeryl.KeyedEntity
import java.util.Date

class Echo(
        val id: String,
        val updatedOn: Date,
        val createdOn: Date,
        val partnerId: String,
        val echoedUserId: String,
        val facebookPostId: String,
        val twitterStatusId: String,
        @deprecated val echoPossibilityId: String,
        val partnerSettingsId: String,
        val echoMetricsId: String,
        val echoClickId: String,
        val step: String,
        val browserId: String,
        val ipAddress: String,
        val userAgent: String,
        val referrerUrl: String,
        val view: String,
        val customerId: String,
        val boughtOn: Date,
        val orderId: String,
        val productId: String,
        val price: Float,
        val landingPageUrl: String,
        val productName: String,
        val category: String,
        val brand: String,
        val description: String,
        val imageId: String) extends KeyedEntity[String] {

    def this() = this(
            id = "",
            updatedOn = new Date,
            createdOn = new Date,
            partnerId = "",
            echoedUserId = "",
            facebookPostId = "",
            twitterStatusId = "",
            echoPossibilityId = "",
            partnerSettingsId = "",
            echoMetricsId = "",
            echoClickId = "",
            step = "",
            browserId = "",
            ipAddress = "",
            userAgent = "",
            referrerUrl = "",
            view = "",
            customerId = "",
            boughtOn = new Date,
            orderId = "",
            productId = "",
            price = 0f,
            landingPageUrl = "",
            productName = "",
            category = "",
            brand = "",
            description = "",
            imageId = "")

    def convertTo(image: domain.Image) = domain.Echo(
            id,
            updatedOn,
            createdOn,
            partnerId,
            echoedUserId,
            facebookPostId,
            twitterStatusId,
            echoPossibilityId,
            partnerSettingsId,
            echoMetricsId,
            echoClickId,
            step,
            browserId,
            ipAddress,
            userAgent,
            referrerUrl,
            view,
            domain.Order(id, updatedOn, createdOn, customerId, boughtOn, orderId),
            domain.Product(id, updatedOn, createdOn, productId, price, landingPageUrl, productName, category, brand, description),
            image)
}
